apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: heartbeat
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true
images:
- name: heartbeat-api
  newName: fernanduandrade/heartbeat-api
  newTag: 57bc935
configMapGenerator:
- literals:
  - IMAGE_TAG=57bc935
  name: app-version-cm
