apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: heartbeat-api
  newName: fernanduandrade/heartbeat-api
  newTag: 57bc935
configMapGenerator:
- literals:
  - IMAGE_TAG=57bc935
  name: app-version-cm
