apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: app-version-cm
    literals:
      - IMAGE_TAG=cb7c3ff
images:
- name: heartbeat-api
  newName: fernanduandrade/heartbeat-api
  newTag: cb7c3ff
